### ISSUE TITLE
Module 'authClient.services' is not available in OS-viewer

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/platform#11]
Receiving an error from the OS-Viewer on the OBEU-Server.
http://eis-openbudgets.iais.fraunhofer.de/viewer/
Maybe due to some misconfiguration on my side.
Have defined this Environment variable:
OS_VIEWER_AUTH_HOST=http://next.openspending.org

Error: [$injector:modulerr] Failed to instantiate module Application due to:
[$injector:modulerr] Failed to instantiate module authClient.services due to:
[$injector:nomod] Module 'authClient.services' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.7/$injector/nomod?p0=authClient.services

**Comment by akariv** [comment]
This code comes from the library at http://next.openspending.org/user/lib

Adan

**Comment by schmaluk** [comment]
Thanks @akariv, I have updated the os-viewer to the latest commit in the master. But the error remains the same: http://eis-openbudgets.iais.fraunhofer.de/viewer/
Will investigate as well.

**Comment by schmaluk** [comment]
@akariv Trying to debug: http://eis-openbudgets.iais.fraunhofer.de/viewer/ in my browser console. Would need a bit of help here. Would that mean that I need to host the library at http://next.openspending.org/user/lib on our server? 
I see in the brwoser console that a GET-request goes to http://next.openspending.org/permit/lib instead of /user/lib.
And the /permit/lib returns 302.
Maybe that is the root cause(?)
Thanks

**Comment by schmaluk** [comment]
Ok, found the error. Somehow in the footer the URL http://next.openspending.org/permit/lib is used and not http://next.openspending.org/user/lib 
So I have hardcoded the proper URL in the footer.
Thanks for the hint Adam.
