### ISSUE TITLE
Due dates for work items for the prototype (Due date: 30.9)

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/platform#15]
#1. Datamining

| Status | Priority | ID | Task Description | Due date for Integration | Assignees | Github-Issue |
| --- | --- | --- | --- | --- | --- | --- |
| open | high | (1.a) | Transformation of OBEU-RDF-datasets into Datamining-CSV (by LinkedPipes) | ? | UEP/FhG/UniBonn @ChristianeEngels | https://github.com/openbudgets/platform/issues/14 |
| dismissed | - | (1.b) | Eventually uploading the Datamining-CSVs to OS-filestorage to get the benefits of OS-apps | ? | FhG/OKI @mlukasch @pwalsh @akariv | ? |
| open | high | (1.c) | Datamining Visualisation/Frontend | Aug. 31, 2016 | FhG/OKG/UniBonn @HimmelStein @mlukasch @larjohn | https://github.com/openbudgets/DAM/tree/tiansi |
| open | high | (1.d) | Datamining Backend/Wrapper for Executing Datamining Algorithms | Aug. 31, 2016 | UEP/FhG/UniBonn @HimmelStein @mlukasch | https://github.com/openbudgets/DAM/tree/tiansi |
| open | high | (1.e) | Datamining Algorithms | ? | UEP/FhG @ChristianeEngels | ? |
#2. OBEU data processing

| Status | Priority | ID | Task Description | Due date for Integration | Assignees | Github-Issue |
| --- | --- | --- | --- | --- | --- | --- |
| open | high | (2.a) | Identify & Upload relevant OBEU-datasets to our OBEU server via LinkedPipes | ? | ETL-Pipeline-Developers @ UEP/FhG/UniBonn/OKG @jindrichmynarz @jakubklimek @ChristianeEngels @fathoni @marek-dudas @datamining_ppl | Identify Task: https://github.com/openbudgets/platform/issues/16 , Upload Task: https://github.com/openbudgets/platform/issues/13 |
| open | high | (2.b) | Testing FDP-to-RDF-pipeline with real FDP data from OpenSpending | ? | FhG/UniBonn/UEP @HimmelStein @mlukasch @marek-dudas | ? |
| open | high | (2.c) | Connecting OS-packager with our endpoint | ? | OKI (FhG) @akariv | https://github.com/openbudgets/platform/issues/5 |
| postponed | - | (2.d) | Define & Provide a Clearance/Synchronisation Pipeline validating & enhancing RDF-data-files & Staging data being transferred to Production Triplestore | ? | UEP (OKG) @jakubklimek @jindrichmynarz @marek-dudas (@larjohn) @datamining_ppl | https://github.com/openbudgets/platform/issues/6 |
#3.OBEU-Dataset visualisation

| Status | Priority | ID | Task Description | Due date for Integration | Assignees | Github-Issue |
| --- | --- | --- | --- | --- | --- | --- |
| open | ? | (3.a) | UI-Integration: Adapt OS-Viewer to OBEU design/Needs | ? | FhG (OKI/OKG) @mlukasch @larjohn | ? |
| open | ? | (3.b) | Eventually implementing a Search engine using the Triplestore (OBEU-equivalent of OS-Conductor) | @mlukasch @pwalsh @jakubklimek @larjohn @akariv @jindrichmynarz | FhG/OKI/OKG | https://github.com/openbudgets/platform/issues/17 |
| integrated | high | (3.c) | Improving Rudolf | ? | OKG (UniBonn) @larjohn @fathoni | https://github.com/openbudgets/rudolf |
#4.Misc

| Status | Priority | ID | Task Description | Due date for Integration | Assignees | Github-Issue |
| --- | --- | --- | --- | --- | --- | --- |
| open | minor | (4.a) | Restricting the endpoint for triggering the FDP-to-RDF-Pipeline via Tokens or BasicAuth | ? | FhG OKI @mlukasch @akariv @pwalsh | ? |
| open | minor | (4.b) | AlignmentUI | ? | OKG @larjohn | ? |

Hello everyone, 

since it is crucial for the success of the project to complete the prototype of our OBEU platform by the 30th September, **please provide the "due date for integration" in the tables above by adding a comment below**, if you have been correctly assigned.

You might want to have some of the work items changed, if you think, those are not properly identified, even missing, not correctly assigned or need to be splitted up further.

**Please feel invited to comment.**

So it will be easier for everyone (including also me) to keep track of open items and to initiate countermeasures/help in case of delays or difficulties.

(Please contact me in any case, if you think there is already something missing which can & should be integrated into the platform/our OBEU server right now.)

It would be nice to add further responsible persons for this task as assignees (for example in datamining), since I dont have all contact addresses on github. Some might have not been added yet to the openbudgets-project.

Thanks a lot for your help & time!

**Comment by pwalsh** [comment]
@mlukasch 

```
Eventually uploading the Datamining-CSVs to OS-filestorage to get the benefits of OS-apps
```

On last tech call the claim was made that the CSVs for data mining are not the same as the raw CSV files published, and therefore AFAIK there is no feature/use case here. ( cc @jindrichmynarz @ChristianeEngels )

**Comment by schmaluk** [comment]
Thanks for the Feedback @pwalsh. Will remove it then, if this doesnt make sense for the datamining.

**Comment by jakubklimek** [comment]
@mlukasch Regarding (2.d), I though we solved this for the September prototype by cloning staging to production. Therefore, this can be developed later. Is this a list of tasks to be done for the prototype (in which case I would remove it) or for the whole platform (in which case we can establish a due date after September?)

**Comment by schmaluk** [comment]
@jakubklimek Thanks. I had assumed that the "real" solution would be used for the prototype. So I will remove it then/mark accordingly as well.

**Comment by jindrichmynarz** [comment]
1.a: Resolving this issue depends on telling which data mining tasks are feasible, produce interesting results, and can be launched interactively by end users. Until then (which will probably happen no sooner than the first OBEU prototype) CSVs for data mining will be produced as ad hoc views for one-off data mining tasks.

2.a: In order to avoid wasted effort, we users of data from [openbudgets/datasets](https://github.com/openbudgets/datasets) should mark which datasets they actually use. For example, I suspect the data from Děčín or Ústecký region was only used to illustrate the infeasibility of tracing EU funds. Once we know which datasets are used, we can migrate only those. We can spin off a separate issue for marking the used datasets.

2.d: Who should define the requirements the clearance and synchronization should implement?

**Comment by schmaluk** [comment]
Hello, 
(2.d) The triplestore data is atm only used by the visualisation (Rudolf). Not by datamining. 
So it would make sense to collaborate with OKG @larjohn about the spec of the clearance & synchronisation. But since the clearance & synchronisation will not be part of the prototype as @jakubklimek noted, the spec itself can also be done at some later Point.

(1.a) I have to ask also here @FhG, if we can agree to skip datamining for the prototype in the worse case, since the datamining part seems to need more time to evolve.

**Comment by jindrichmynarz** [comment]
One point to clarify: Clearance pipeline applies not only to data in the RDF store, but also to RDF dumps, which should contain the same data as the RDF store. Hence, this is also a concern for data mining that uses RDF dumps (e.g., to produce CSV views).

Regarding 1.a, I don't think it is necessary to skip data mining entirely, as some parts of it are already worked on for some time, such as outlier detection, and may be ready in time for the prototype.

**Comment by pwalsh** [comment]
hmmm.

@badmotor I'm closing this. It must be out of date, and any specific issues can be raised with distinct issues.
