### ISSUE TITLE
OBEU-Search for Rudolf

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/platform#17]
Here we can discuss, whether a dedicated OBEU-Search is necessary or not and should also be part of the prototype and how to implement it.

By using OS-Search atm we get a lot of results in the OS_Viewer on our server, which are not stored in our triplestore. Since we maybe wont have the same datasets stored in our triplestore as OpenSpending has, we would need a Search querying the datasets on the OBEU-server.

**Comment by jindrichmynarz** [comment]
Is full-text search necessary for some use cases? If so, I think we can easily extend Apache Jena's Fuseki with [additional full-text indices](https://jena.apache.org/documentation/query/text-query.html).

**Comment by schmaluk** [comment]
Thanks @jindrichmynarz. OpenSpending uses ElasticSearch. So I think it also uses full-text search. @pwalsh Do you also think we should work on this for the prototype? Can try an implementation based on Fuseki then. But would need probably some help from OKI to make it compatible to the OS-Viewer.

**Comment by jindrichmynarz** [comment]
Let's not implement it until we clarify if it is actually needed in the use cases.

**Comment by pwalsh** [comment]
@badmotor I'm closing this. It must be out of date, and any specific issues can be raised with distinct issues.
