### ISSUE TITLE
OS-Viewer: DataMining-Button's URL

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/platform#21]
@larjohn @akariv @pwalsh Hello, Im opening a new issue for this one.
But this one is related to: https://github.com/openbudgets/platform/issues/18

A click on the DataMining-Button in the Viewer:
http://next.openspending.org/viewer/da34ef6cdb3c6dc3f21686ebcaa2f74b:testfdp3?lang=en
results in the following URL:
http://next.openspending.org/?queryText=SELECT%20*%20FROM%20fdp__da34ef6cdb3c6dc3f21686ebcaa2__testfdp3%20LIMIT%2010&focusedTable=fdp__da34ef6cdb3c6dc3f21686ebcaa2__testfdp3&jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE0NzgwMDEzOTcsInVzZXJpZCI6ImRhMzRlZjZjZGIzYzZkYzNmMjE2ODZlYmNhYTJmNzRiIn0.43hN8B5d5NLbUthOul2Qawnibt0dgjTnNXvgM4W41yw

So far just the DataMining-Host is configurable but not the Query-Parameters of the URL, if Im not mistaken

As far as I can see, if we want to show the DataMining Page in Indigo for the selected dataset, we'd need here further adaptions.

That means either Indigo would need to extract the information from the queryText to get the specific dataset id or the OpenSpending-Viewer needs to have another way of passing the information such as the dataset id via Query-Parameters. 
As an additional alternative to this an OBEU-specific version of:
https://github.com/openspending/os-viewer/blob/master/app/front/scripts/directives/package-info/index.js
 can be copied into the Dockerfile for the Viewer before the build-phase with a definition of different Query-Parameters.

Im not sure which way would be the best regarding the remaining week until the end of the month.
If thats not possible anymore, I'll hope we can at least find a way to make it work without errors.
At least I'd be glad to have your opinion about it.
Thanks for your time.

**Comment by pwalsh** [comment]
when this came up in a tech call, it was said the URL was fine, and the query itself is managed on the data mining app.

**Comment by pwalsh** [comment]
I see @akariv addressed this in the original issue, so not sure we need another issue for this. Maybe we should close this?
