### ISSUE TITLE
Fix in FDP-to-RDF-pipeline needed (for demonstrating integration work)

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/platform#23]
Hello @marek-dudas ,

sorry to address you via Email & github redundantly. (Due to the urgency of the matter I have used both ways.)
The Problem:
The FDP-RDF datasets come with a dc-elements instead of a dc-terms title. According to @jakubklimek , the latter should be used. Without this fix we dont see the Datasets imported by the FDP-to-RDF-pipeline in the Explorer: http://eis-openbudgets.iais.fraunhofer.de/explorer

Remark: We would need to create a screencast to demonstrate the integration work for the plenary.
Therefore the urgency.
That would be really really helpful.
Thanks a lot!

**Comment by marek-dudas** [comment]
Should now be fixed in the 0.7.1 version of the pipeline in [commit 2521569](https://github.com/openbudgets/pipeline-fragments/commit/25215692314b7c446f0ff9286252433f27b6f36e). Just the pipeline needs to be updated, no changes in the FDPtoRDF component.
