### ISSUE TITLE
User-Feedback when FDP-to-RDF-pipeline completed

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/platform#25]
Hello,
since we tend now to include the FDP-to-RDF-pipeline in the LST, there has been another request in the last tech call.
When the user triggers the FDP-to-RDF-pipeline, there should be some kind of feedback to the user, when and if the pipeline has been completed correctly.

I'd be very glad about your input what this user feedback should look like (maybe the easiest: a Email notification to the user) and if this could be done, should changes be necessary for example at OS-side for this. If so, I can try to do/help this.
I think there was way to check if a pipeline has been completed in LinkedPipes.
Thanks a lot for your help

**Comment by jindrichmynarz** [comment]
One approach to do this could be that the pipeline can trigger a GET request after it's done processing (using the "run before" edge). The requested URL can implement a simple service that would notify the user.

A trickier subject is to decide what should the exchanged messages contain. The FDP2RDF pipeline can send some fields from its input FDP descriptor (e.g., `author`) along with the named graph IRI of the produced dataset. This may or may not be enough to cover our use cases.

**Comment by jakubklimek** [comment]
I think that the proposed approach here is to use the existing LP-ETL API to monitor the pipeline execution (and possibly display its state) in an external tool. Therefore this tool can notify the user once it sees that the execution is finished.

**Comment by jindrichmynarz** [comment]
Yes, monitoring the LP-ETL API directly is a superior solution.

**Comment by schmaluk** [comment]
Hi, many thanks. So I could/should write such a tool which monitors the LP-ETL-API in order to find recently completed FDP-to-RDF-pipeline jobs. Can the email address of the user somehow be retrieved by the LP-ETL API for the FDP-to-RDF-pipeline jobs? Or is the email address not at all provided to the FDP-to-RDF-pipeline from OS-side?

**Comment by jakubklimek** [comment]
There are no users in LP-ETL and the email address is not passed to LP-ETL. Since the email address in question is the address of the OS user, I could imagine a simplified execution monitor showing only statuses of FDPtoRDF pipeline executions of that given user, possibly notifying him using is OS-registered email address.

Is this functionality required? As far as I know there is only a simple hook in OS to run the pipeline right now, so this would mean creating a OBEU specific piece of SW to be integrated with OS and LP-ETL.

**Comment by schmaluk** [comment]
Apparently the user mail address is somehow contained in the author field in the datapackage.json:
"author": "XX YY<xxyy@xyz.com>"
```
{
  "model": {
    "dimensions": {
      "date": {
        "dimensionType": "datetime",
        "primaryKey": [
          "DATA_AGGIORNAMENTO"
        ],
        "attributes": {
          "DATA_AGGIORNAMENTO": {
            "source": "DATA_AGGIORNAMENTO",
            "title": "DATA_AGGIORNAMENTO"
          }
        }
      }
    },
    "measures": {
      "TOT_PAGAMENTI": {
        "source": "TOT_PAGAMENTI",
        "title": "TOT_PAGAMENTI",
        "currency": "USD"
      }
    }
  },
  "title": "fdptest",
  "name": "fdptest",
  "description": "fdptest",
  "resources": [
    {
      "name": "pag_fs0713_lom_20160630",
      "format": "csv",
      "path": "pag_FS0713_LOM_20160630.csv",
      "mediatype": "text/csv",
      "bytes": 673073006,
      "dialect": {
        "csvddfVersion": 1,
        "delimiter": ";",
        "lineTerminator": "\n"
      },
      "encoding": "utf-8",
      "schema": {
        "fields": [
          {
            "title": "DATA_AGGIORNAMENTO",
            "name": "DATA_AGGIORNAMENTO",
            "slug": "DATA_AGGIORNAMENTO",
            "type": "integer",
            "format": "default",
            "osType": "date:fiscal-year",
            "conceptType": "date"
          },
          {
            "title": "TOT_PAGAMENTI",
            "name": "TOT_PAGAMENTI",
            "slug": "TOT_PAGAMENTI",
            "type": "number",
            "format": "default",
            "osType": "value",
            "conceptType": "value",
            "decimalChar": ".",
            "groupChar": ","
          }
        ],
        "primaryKey": [
          "DATA_AGGIORNAMENTO"
        ]
      }
    }
  ],
  "@context": "http://schemas.frictionlessdata.io/fiscal-data-package.jsonld",
  "owner": ".......",
  "author": "XX YYY <xxxyyy@zzz.com>"
}
```
located at 
https://s3.amazonaws.com/datastore.openspending.org/ ...  /fdptest/datapackage.json
If the author field of the datapackage.json or the whole datapackage.json or its URL can be retrieved by the LP-ETL API, we have the mail address

**Comment by jakubklimek** [comment]
I think it should be the other way around. The "manager" (the proposed new SW) should pair the OS user (and his email) and the execution ID (to be monitored), since OS creates the execution and passes the data package to LP-ETL. Extracting the datapackage.json from LP-ETL when it is being sent there by OS in the first place does not seem efficient.

**Comment by jindrichmynarz** [comment]
Moreover, is the user that triggers the pipeline execution always the same as the `author` in FDP descriptor? I think users can take FDPs made by others and convert them to RDF. The user to notify should be better provided via OS.

**Comment by marek-dudas** [comment]
During today's tech-call, we agreed with @pwalsh not to expose the OS users' emails and just add status info directly into the OS packager/admin interface. The user could login later and re-check whether the pipeline finished successfuly. @jakubklimek, is there documentation of the abovementioned LP-ETL API for getting the pipeline execution progress info? Or maybe even better, could you get in touch with @pwalsh so that you could discuss directly how to arrange the implementation in the OS packager?

**Comment by pwalsh** [comment]
@jakubklimek @akariv 

We agreed something like this should work (please both confirm, and @jakubklimek also we'd need to know how to do this with LPETL APIs):

- Packager sends the payload
- LPETL gives an identifier
- Packager polls an endpoint from LPETL at intervals, using the identifier, to get the state of the pipeline
- Presumably three states are useful: pending, success, failure
- OS then uses this state to indicate to user that status of pipeline

**Comment by akariv** [comment]
This is done via OS-Admin but other than that this sounds good.

One thing to note is that we'll do it on the client side, so this state will not persist across page refreshes.

**Comment by jakubklimek** [comment]
I dont recall if we discussed this before, but this is definitely possible.
There are currently two ways to do this (as the current LP-ETL frontend does it)
1) The easiest is the list of all executions, including their statuses. With an execution ID, one can find his execution and its status: http://demo.etl.linkedpipes.com/resources/executions
2) Then there is detailed info of a specific execution, however, this is lots of data as it contains a complete status of the execution, which is unnecessary for a simple status report: http://demo.etl.linkedpipes.com/resources/executions/ac6b375e-36f0-4a55-9b6f-bd09316f74d6

We (@skodapetr) are also planning to do a shorter response for a specific pipeline, which could be ideal for this and can be ready next week.

**Comment by pwalsh** [comment]
@jakubklimek can LPETL use an identifier that OS-Admin can pass? Then, OS-Admin can poll as per my original outline, and we don't have a page refresh problem as per the comment from @akariv

**Comment by jakubklimek** [comment]
@pwalsh When OS runs the FDP2RDF pipeline (creates its execution), the execution ID (created in LP-ETL) is returned and can be used to determine the status of the execution via one of the two ways described above.

If I understand it correctly, you would like it the other way around? I.e. the ID to be created in OS-Admin, passed to LP-ETL and used by OS-Admin to determine the execution status?

**Comment by pwalsh** [comment]
@jakubklimek yes, it would be useful, if it is possible.

**Comment by jakubklimek** [comment]
@pwalsh OK, then it should look like this:
1. OS-Admin creates and ID and sends it along with FDP to LP-ETL for processing
2. OS-Admin polls LP-ETL using this ID for execution status
right?

How will this ID look like? OS-Admin will then be responsible for generating unique IDs?

**Comment by pwalsh** [comment]
@jakubklimek yes, this would allow OS-Admin to retrieve  pipeline static without having its own database. I imagine that, on submitting an FDP descriptor to LPETL, OS Admin could create a hash from the descriptor, and pass that as the "job ID" and use the same hash to poll for status. This then means that even with page reloads etc, the Admin can still generate the same hash to poll LPETL.

@akariv any issues here I do not foresee?

**Comment by jakubklimek** [comment]
@pwalsh This would mean that the hash would be always the same for the same descriptor, i.e. not unique for individual executions. Therefore, before each run of the pipeline, the old execution would have to be deleted or something like that

**Comment by pwalsh** [comment]
@jakubklimek good point. It makes me think that we should also use this to ensure that a user does not trigger multiple executions for the same descriptor. i.e., OS Admin can poll before a new submission, if the hash has a pipeline status of anything but success, then, tell the user that she can't trigger a new job as there is already one in process.

**Comment by pwalsh** [comment]
If the above works, it reduces load on LP-ETL, but if you need a guarantee that the hash is a unique identifier, we could possibly hash with descriptor + timestamp or something.

**Comment by jindrichmynarz** [comment]
Why not use a UUID?

**Comment by jakubklimek** [comment]
@pwalsh This is not currently supported in LP-ETL so we would need to develop it anyway, it is just a question of specification. But including a timestamp in the hash would negate the original motivation, as you would need to store the timestamp somewhere right?

@jindrichmynarz The same problem with UUID, the used UUID would need to be additionally stored by OS-Admin, therefore it is similar to storing the execution UUID already generated by LP-ETL.

**Comment by jindrichmynarz** [comment]
Ah, I see, OS would not persist it on page reloads.

**Comment by jindrichmynarz** [comment]
From the architectural standpoint, I think LP-ETL is responsible for the execution process, so it should be responsible for providing it with an identifier. Does it really take that much server-side code in OS to persist the execution ID over page reloads?

**Comment by pwalsh** [comment]
ok, I talked with @akariv and we'll just use the ID provided by LP-ETL.

**Comment by akariv** [comment]
Sorry for not following properly on this thread - but this got very complicated real quick :)
Unless it's an absolute requirement, the page refresh persistence is something that I would definitely drop. To implement it would incur either (1) to persist execution ids on the server, which I don't want to do or (2) to poll LP-ETL for execution status on page load for every dataset for every user. 
Both options don't make sense to me for such a small (and infrequently used) feature.

I suggest we go with the simple solution - LP-ETL returns the execution id to OS, OS-Admin then polls a URL with the execution id for the execution status.
It continues polling until:
- A finite state is achieved (i.e. finished successfully or failed)
- A polling error occurred (e.g. a 404 response)
- The page was refreshed

Does this sound reasonable to everyone?

**Comment by marek-dudas** [comment]
Ok then. Maybe there could be some note like "If you leave this page, you won't get informed about the execution status anymore" included in the OS-Admin?

**Comment by akariv** [comment]
Sure thing.

**Comment by jindrichmynarz** [comment]
If persistence across multiple requests is required, while maintaining server side state is undesirable, how about persisting pairs of LP-ETL execution ID and OS ID in `Window.localStorage`?

**Comment by akariv** [comment]
If persistence is required, we'll store it on the server. 

But is it required? What's the use case? Who is the user? How frequently will this feature be used?

**Comment by jindrichmynarz** [comment]
The issue of persistence was originally brought up by @pwalsh [above](https://github.com/openbudgets/platform/issues/25#issuecomment-280382647), but I don't think it is required at this point.

**Comment by pwalsh** [comment]
Under review from another angle now.
