### ISSUE TITLE
Problem with bulk upload in Virtuoso

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/platform#28]
The bulk upload does not work properly yet.
It hangs.
Maybe you might have an advice for me what I can do differently.
Would be much appreciated. 

This is my virtuoso.log:
```
12:50:50 Server online at 1111 (pid 63)
12:52:19 PL LOG: Loader started
12:52:25 PL LOG:  File /upload/skos.ttl error 37000 SP029: TURTLE RDF loader, line 2: syntax error processed pending to here.
12:52:25 PL LOG: No more files to load. Loader has finished,
12:55:43 * Monitor: Locks are held for a long time
12:57:58 * Monitor: Locks are held for a long time
```
This is my script:
https://raw.githubusercontent.com/openbudgets/integration/master/docker-config/virtuoso/cronjobs/importFromTrig

Here my virtuoso.ini:
https://raw.githubusercontent.com/openbudgets/integration/master/docker-config/virtuoso/staging/virtuoso.ini

**Comment by jakubklimek** [comment]
Unfortunately this is a known issue with Virtuoso (I reported it first in 2014) and it is still unsolved. When this happens, I usually need to restart the virtuoso instance.
https://github.com/openlink/virtuoso-opensource/issues/165
https://github.com/openlink/virtuoso-opensource/issues/271

**Comment by jindrichmynarz** [comment]
Then it is probably better to avoid using multiple threads to load data. I don't think that the performance slowdown will matter for our use cases.

**Comment by schmaluk** [comment]
Thanks it works now with the restart.

**Comment by jindrichmynarz** [comment]
Moreover, isn't it better to leave some cores for handling query load while new data is loaded? I think single-threaded loading should be fine.

**Comment by schmaluk** [comment]
Hello yes, I think that it is single threaded atm.
There is just a single call of rdf_loader_run() in the import-scripts at least.
