### ISSUE TITLE
OS-Explorer issues at Fhg

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/platform#30]
http://eis-openbudgets.iais.fraunhofer.de/explorer

- Remove/Substitute Mr Placeholder as Owner
- Imported datasets by the FDP-to-RDF-pipeline are not shown up in the OS-Explorer Search
- Links in the Search in OS-Explorer are directing to next.openspending.org and not to eis-openbudgets.iais.fraunhofer.de

**Comment by schmaluk** [comment]
* Mr. Placeholder: https://github.com/openbudgets/rudolf/issues/23
* fixed: Links in the Search in OS-Explorer are directing to next.openspending.org and not to eis-openbudgets.iais.fraunhofer.de

**Comment by pwalsh** [comment]
@badmotor

Should this be kept open, for action, or not. If it should be actioned, let's assign a single person with responsibility, and get an estimate on time and due date.

**Comment by pwalsh** [comment]
@pierorex @liyakun is someone responsible for this issue?

**Comment by pierorex** [comment]
Well, not me, but I think @lavdim is the one maintaining this now with @liyakun 's help, but Lavdim is on vacation now

**Comment by pwalsh** [comment]
@pierorex so who is responsible at Fraunhofer for assigning tasks and so forth?

**Comment by pierorex** [comment]
@pwalsh that would be Fabrizio, he's the big boss in the team

**Comment by liyakun** [comment]
@pwalsh @badmotor I think this can be closed now, as we decided to use Indigo to replace os-explorer on Fraunhofer server. How do you think?

**Comment by liyakun** [comment]
as we are not going to use os-expolrer anymore at the Fraunhofer server, so I will close this issue.
