### ISSUE TITLE
OS Viewer issues in OBEU

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/platform#31]
- Message showing up: "You have selected no Datasets" even if there is a dataset selected
- Set refreshing of the Cache in Rudolf to 30 mins intervals via Cronjobs

**Comment by schmaluk** [comment]
* done: Set refreshing of the Cache in Rudolf to 30 mins intervals via Cronjobs
Refreshing of the Cache in Rudolf is necessary for the new result showing up at the endpoint: http://eis-openbudgets.iais.fraunhofer.de/search/package

**Comment by pwalsh** [comment]
Seems to be fixed.
