### ISSUE TITLE
RDFBrowser not working

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/platform#33]
Hi,
I am trying to access a resource 
http://data.openbudgets.eu/data/dataset/budget-athens-expenditure-2008

It returns an error related to SQLite. 
```
PDOException in Connector.php line 55: could not find driver
```

This might be because of a missing php module?

http://php.net/manual/en/sqlite.installation.php

**Comment by schmaluk** [comment]
Hello @skarampatakis should be fixed by now.

**Comment by skarampatakis** [comment]
Yes it is fixed. If you could perform an update on RDFBrowser it would be perfect. I have made some performance improvements.
