### ISSUE TITLE
Datasets not shown in OS-Viewer

### ISSUE THREAD

**Issue by schmaluk** [openbudgets/platform#34]
Hello @fathoni, CC: @larjohn
just a small thing. (Not urgent probably)

some of the datasets (for example: Aragon 2006) are not properly shown in the OS-Viewer:
http://eis-openbudgets.iais.fraunhofer.de/viewer/aragon-2006-expenditure__a0a36?lang=en

The facts-endpoint in Rudolf seems not to return the whole datasets:
http://eis-openbudgets.iais.fraunhofer.de/api/3/cubes/aragon-2006-expenditure__a0a36/facts

In contrast to:
http://eis-openbudgets.iais.fraunhofer.de/api/3/cubes/aragon-2007-expenditure__70f3d/facts

Maybe Aragon-2006 and possibly other datasets as well are not properly imported into Virtuoso (?)
I checked at the SPARQL-endpoint http://data.openbudgets.eu/sparql:
```
SELECT ?subject  ?predicate ?object
FROM <http://data.openbudgets.eu/resource/dataset/aragon-2006-expenditure>
WHERE {
  ?subject ?predicate ?object
}
```
But unfortunately Im not able to validate the datasets in Virtuoso.

**Comment by schmaluk** [comment]
It seems those datasets are effected as well:
http://eis-openbudgets.iais.fraunhofer.de/viewer/budget-heraklion-expenditure-2015__a9652?lang=en
http://eis-openbudgets.iais.fraunhofer.de/viewer/budget-heraklion-expenditure-2014__afb8a?lang=en
http://eis-openbudgets.iais.fraunhofer.de/viewer/budget-heraklion-expenditure-2013__2c4eb?lang=en
http://eis-openbudgets.iais.fraunhofer.de/viewer/budget-heraklion-expenditure-2012__9a434?lang=en
http://eis-openbudgets.iais.fraunhofer.de/viewer/budget-heraklion-expenditure-2011__1a1e8?lang=en
http://eis-openbudgets.iais.fraunhofer.de/viewer/budget-heraklion-expenditure-2010__4c7cc?lang=en
http://eis-openbudgets.iais.fraunhofer.de/viewer/aragon-2016-income__2a454?lang=en

**Comment by larjohn** [comment]
I haven't found what's going wrong yet. This will be resolved during the weekend so please continue with the other datasets.

**Comment by larjohn** [comment]
Regarding the Aragon 2006 dataset, the facts are missing the qb:Observation type:

`describe <http://data.openbudgets.eu/resource/dataset/aragon-2006-expenditure/observation/10>
`

**Comment by larjohn** [comment]
Regarding the Heraklion datasets, they define `http://data.openbudgets.eu/ontology/dsd/greek-municipalities/dimension/budgetPhase` as a dimension but use `http://data.openbudgets.eu/ontology/dsd/dimension/budgetPhase` instead

**Comment by pwalsh** [comment]
@badmotor @larjohn @skarampatakis 

Should this be kept open, for action, or not. If it should be actioned, let's assign a single person with responsibility, and get an estimate on time and due date.

**Comment by pwalsh** [comment]
Closing as no clear responsibility, and, it seems that, as discussed elsewhere, this is an issue of what data is available from the APIs.
