### ISSUE TITLE
OS-Viewer not working

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/platform#36]
Hi, I am trying to access a dataset from the OS-explorer. Explorer seems to be working.
Clicking on a dataset redirects on OS-Viewer. But then it stacks on loading. Please find below the console messages. 

```
XMLHttpRequest cannot load http://next.openspending.org/user/check?next=http:%2F%2Feis-openbudgets.iais.fraunhofer.de%2Fviewer%2Fbudget-athens-expenditure-2008__cbe9f. Redirect from 'http://next.openspending.org/user/check?next=http:%2F%2Feis-openbudgets.iais.fraunhofer.de%2Fviewer%2Fbudget-athens-expenditure-2008__cbe9f' to 'https://next.openspending.org/user/check?next=http:%2F%2Feis-openbudgets.iais.fraunhofer.de%2Fviewer%2Fbudget-athens-expenditure-2008__cbe9f' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://eis-openbudgets.iais.fraunhofer.de' is therefore not allowed access.


angular.js:14516 Possibly unhandled rejection: {"data":null,"status":-1,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","params":{"next":"http://eis-openbudgets.iais.fraunhofer.de/viewer/budget-athens-expenditure-2008__cbe9f"},"withCredentials":false,"url":"//next.openspending.org/user/check","headers":{"Accept":"application/json, text/plain, */*"}},"statusText":""}
(anonymous) @ angular.js:14516
```

Neither this [link](http://eis-openbudgets.iais.fraunhofer.de/viewer/budget-thessaloniki-revenue-2011__80bce?lang=en&measure=amount.sum&groups%5B%5D=economicClassification.notation&filters%5BbudgetPhase.budgetPhase%5D%5B%5D=http%3A%2F%2Fdata.openbudgets.eu%2Fresource%2Fcodelist%2Fbudget-phase%2Fapproved&visualizations%5B%5D=Treemap) seems to be working, taken from KPI app.

**Comment by larjohn** [comment]
Also referenced [here](https://github.com/openbudgets/rudolf/issues/22#issuecomment-296662238)

**Comment by larjohn** [comment]
@liyakun I have made a couple of commits in the integration repo, to change where the authentication requests go. 

Obviously they are not going to work directly. First, let's try to make http://eis-openbudgets.iais.fraunhofer.de/user/lib work as expected - you need to allow this to reach rudolf through nginx. I am not aware how to do this myself. When successful, a javascript file will be available there. This script is actually the authentication library used by OpenSpending Viewer and OpenSpending Explorer. 

I have updated Rudolf to serve this file with an altered endpoint passing through https://cors-anywhere.herokuapp.com/ (more info [here](https://github.com/Rob--W/cors-anywhere)). This temporarily resolves the CORS blocking issue.

**Comment by liyakun** [comment]
@larjohn I configured nginx to make http://eis-openbudgets.iais.fraunhofer.de/user/lib reach rudolf, now os-viewer is working, thank you very much. I am not sure should we keep this issue open until a better solution is found.

**Comment by pwalsh** [comment]
@badmotor closing this. looks finished.
