### ISSUE TITLE
Update RDFBrowser 

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/platform#37]
Hi @wk0206,

could you update the RDFBrowser to the latest version? It seems that till now an outdated version is used.

**Comment by pwalsh** [comment]
@badmotor @skarampatakis 

Who is responsible for this? Can we get a due date, etc.

**Comment by skarampatakis** [comment]
I think it is on the Fraunhofer side.

**Comment by pwalsh** [comment]
@liyakun is this something you will do, and, when?

**Comment by liyakun** [comment]
@pwalsh thanks for your remind, I just updated the RDFBrowser on Fraunhofer server.
