### ISSUE TITLE
RDFBrowser not working properly after update

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/platform#38]
It seems that there is a missing library and RDFBrowser fails to render observation's
For instance check this 

http://data.openbudgets.eu/data/dataset/budget-athens-expenditure-2005/observation/1

That is the mbstring module for PHP, as the defined https://laravel.com/docs/5.4#server-requirements

- PHP >= 5.6.4
- OpenSSL PHP Extension
- PDO PHP Extension
- Mbstring PHP Extension
- Tokenizer PHP Extension
- XML PHP Extension

I will also update RDFBrowser documentation. Is there anything else I can do to eliminate this kind of issues?

**Comment by liyakun** [comment]
@skarampatakis it seems the problem is that mbstring is not enabled, could you check whether the current running RDFBrowser is working as expected?

**Comment by skarampatakis** [comment]
Yes. Now it's perfect. Thank you!

**Comment by liyakun** [comment]
@skarampatakis great, thank you for reporting.

**Comment by liyakun** [comment]
@skarampatakis great, thank you for reporting.

**Comment by skarampatakis** [comment]
Hi @liyakun. This happens again after recent update. 

please check

http://data.openbudgets.eu/data/dataset/budget-athens-expenditure-2005/observation/1

**Comment by liyakun** [comment]
@skarampatakis sorry, I forgot to update my changes to the docker file, it should work now.

**Comment by skarampatakis** [comment]
Yes, Thank you!
