### ISSUE TITLE
os-packager authentication issue

### ISSUE THREAD

**Issue by liyakun** [openbudgets/platform#39]
When a user click on the "Login" or "Register" button, the user will be redirect to http://eis-openbudgets.iais.fraunhofer.de/logged-in?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyaWQiOiI1NTM3MTA0YTkwMmIwODQ3YmI3YjQ3NDIyNWVjZWQ1YSIsImV4cCI6MTQ5NzM0NjA4OH0.2UU4MX1AHqj6qYlFrLfvAckfnnxO311-_GS0mEufnZo#
which is 404 Nor Found error.

@akariv @pwalsh Do you probably know the reason? thanks.

**Comment by pwalsh** [comment]
Hi @liyakun 

This issue duplicates this one: https://github.com/openspending/openspending/issues/1238

So I'll close this, and we'll track it there.

@akariv please schedule this in for fixing asap.

**Comment by akariv** [comment]
This seems to be a local installation issue - as it does not replicate on
the staging and production setups.

**Comment by liyakun** [comment]
@akariv I checked the issue again today and compared with the authentication on openspending.

1. Authentication on http://apps.openbudgets.eu/packager/

- As an existing user, I log out from my current login with os-packager. 
- Then I click on the `Login/Register` again and I am redirected to `https://next.openspending.org/user/check?next=http:%2F%2Fapps.openbudgets.eu%2Flogged-in` in the current brower tap.
- I also have on more tap opened in my current browser, where the url is `http://apps.openbudgets.eu/logged-in?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MDA1NzAwODAsInVzZXJpZCI6IjU1MzcxMDRhOTAyYjA4NDdiYjdiNDc0MjI1ZWNlZDVhIn0.HtRwmZJtSUm1gZnwyil0E7w99ooprKO_iI9jvZGGxkU#`, which is an 404 error.

2. Authentication on https://next.openspending.org/packager/
- As an existing user, I log out from my current login with os-packager. 
- Then I am redirect to `https://next.openspending.org/explorer/?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MDA1NzAyMzAsInVzZXJpZCI6IjU1MzcxMDRhOTAyYjA4NDdiYjdiNDc0MjI1ZWNlZDVhIn0.tYrDiHTnXgjpWn_3onuTYu_ldTPkoZhpCPNHztIORQM#` at the same page.

I don't know whether there is a special setting in https://next.openspending.org, or maybe you are more clear about where the problem happens? Thanks.

**Comment by liyakun** [comment]
@akariv Currently, I use one url redirection to solve this problem.
location ~* ^/logged\-in(.*)$ {
      rewrite ^/logged\-in(.*)$ http://apps.openbudgets.eu/packager/logged-in$1 permanent;
      break;
}

**Comment by akariv** [comment]
This issue was resolved in latest master of os-packager @liyakun
