### ISSUE TITLE
OS Viewer: too many items on particular views

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/platform#41]
In some cases. graphs contain multiple items as parts. It is really cool for the treemap or the bubble chart but when it comes to the pie chart or the radar chart, it renders uselless hard to read and understand graphs. Take a look [here](http://eis-openbudgets.iais.fraunhofer.de/viewer/embed/piechart/budget-thessaloniki-revenue-2011__80bce?measure=%22amount.sum%22&groups%5B%5D=%22economicClassification.notation%22&filters%5BbudgetPhase.budgetPhase%5D%5B%5D=%22http:%2F%2Fdata.openbudgets.eu%2Fresource%2Fcodelist%2Fbudget-phase%2Fapproved%22&order=%22amount.sum%7Cdesc%22&lang=en)

![image](https://cloud.githubusercontent.com/assets/2419820/26711997/fd62fe90-476c-11e7-953a-4e3f549d53ad.png)

Would it be possible that we could limit the number of items shown? Ideally I think that we could show let say n = 5-8 slices with the top n values and aggregate the rest in a n+1 slice under the name "Other". Then if the user wants to see the composition of "Other" , clicks on the slice and gets the pie chart with the same limits as above and so on.

**Comment by pwalsh** [comment]
@skarampatakis I think we addressed this recently. @akariv @vitorbaptista can you confirm?

**Comment by pwalsh** [comment]
Was dealt with in this commit by the looks of it https://github.com/openspending/os-viewer/commit/2c1f3e810aac13647407fb67704fe44f76d7a0ea

**Comment by skarampatakis** [comment]
@liyakun could you update the OS Viewer on the platform?

@pwalsh yes, just saw it looking for the translations. But it is not used on the next.openspending.org platform yet and is only for the pie chart?. 

Also on the commit message it is referred that 

> The slice that groups the smaller values can't be clicked on, as it makes no
sense to drill down in multiple categories.

Could it be possible to have a behaviour as I described above?

**Comment by pwalsh** [comment]
If you can open a dedicated issue on the OpenSpending tracker then it is easier for all the team to see (not everyone on OpenSpending team is on openbudgets).

**Comment by liyakun** [comment]
@skarampatakis The os-viewer has been updated on the Fraunhofer server to latest version https://github.com/openspending/os-viewer/commit/3823010f561ef100a27684be7d6d0ec720371f23.

**Comment by skarampatakis** [comment]
Great! Thanks @liyakun .
