### ISSUE TITLE
OS Viewer: Localization of the interface

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/platform#42]
Currently interface of OS viewer is only shown in English. How can we change UIs language to match user preferences? Is it already i18n capable?

**Comment by pwalsh** [comment]
@skarampatakis this is already supported as I mentioned in a related thread. It would be much easier if you open issues like this on the openspending issue tracker so the whole team there sees it.

See the pattern for adding UI translations at https://github.com/openspending/os-viewer/tree/master/translations

**Comment by skarampatakis** [comment]
@pwalsh Thanks, You are right, I just remembered that you referred it somewhere. I will try to add translations in Greek the sooner possible. But this is only for the Viewer, right?  

I opened this issue as a question actually. I see that in every OS viewer url there is a "lang" variable. But this is retrieved by the browser settings? Can you change language from the interface or just change the lang on the url?

**Comment by pwalsh** [comment]
It needs to be set via the query params. Detection based on browser settings is extremely annoying in many use cases. If you want detection based on browser, we could open a feature request I suppose, and have that option behind an env var.
