### ISSUE TITLE
Login from packager landing page throws error, but works at any other step

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/platform#45]
When try to login from 
```http://eis-openbudgets.iais.fraunhofer.de/packager/```
using the top right login button I get a 404. 

But if I am at ```http://eis-openbudgets.iais.fraunhofer.de/packager/provide-data``` after get started and then click on the login button I get logged successfully.

**Comment by liyakun** [comment]
@skarampatakis I have created this issue before, see https://github.com/openbudgets/platform/issues/39, but did't get time to check exactly how this happen.

**Comment by liyakun** [comment]
@skarampatakis this issue should be fixed now, could you check? If it is solved please help to close the issue. Thanks.

**Comment by liyakun** [comment]
@skarampatakis as this problem has been fixed also in the lastest version of os-packager, I close this issue.

**Comment by skarampatakis** [comment]
I confirm that now I can use the login from local os-packager successfully.

**Comment by liyakun** [comment]
@skarampatakis thanks.
