### ISSUE TITLE
http://data.openbudgets.eu has no useful response

### ISSUE THREAD

**Issue by pwalsh** [openbudgets/platform#47]
# Description

When a user stumbles upon `http://data.openbudgets.eu` there is no data. I assume that, given a correct URL to a dataset, there is a response, powered by OKGR's RDF browser. If the root of the domain has no placeholder, or just a list of datasets, then how about we redirect requests to the root to the location of indigo, so that users can navigate datasets.

# Tasks

- [ ] redirect requests to the root of the domain to the location of Indigo.

@badmotor @larjohn @skarampatakis @jindrichmynarz @seegerseeger thoughts, or alternatives?

**Comment by skarampatakis** [comment]
Hi @pwalsh,
That is indeed an issue of RDFBrowser. It is a really basic 404 page. I had some plans for a landing page where users can have some overview of data within this domain and an entry point to the SPARQL endpoint. Or even some user defined links. But was postponed. I can provide an update for user defined redirection on such case as a temporal solution if it is required today, and a landing page when I will find some time, unless you believe that it is urgent.

**Comment by pwalsh** [comment]
@skarampatakis no worries. in that case, I would recommend that @liyakun or @pierorex just redirect requests that come for the root to indigo, which is the app we are using the browse datasets.

**Comment by skarampatakis** [comment]
Just pushed an update that helps on this issue. https://github.com/okgreece/RDFBrowser/commit/07b770224ae1160a04dd1cb2e8368388c39e38ea
update the app and add

```
APP_DOMAIN_PAGE=false
APP_DOMAIN_REDIRECT=http://example.com
```

on your .env file. Replace http://example.com with whatever will be the redirect.

**Comment by pwalsh** [comment]
@skarampatakis let's leave this open until it is updated on the platform (Fraunhofer server).

**Comment by liyakun** [comment]
@pwalsh @skarampatakis I redirected `http://data.openbudgets.eu` to `http://eis-openbudgets.iais.fraunhofer.de/explorer/` as currently there is a problem with Indigo.

**Comment by pwalsh** [comment]
I don't think you have done it correctly. Example: `apps.openbudgets.eu/explorer/` does not work.

**Comment by liyakun** [comment]
@pwalsh Sorry, I misunderstood your desceiption.

**Comment by liyakun** [comment]
@pwalsh should this be keep open?
