### ISSUE TITLE
Indigo stopped working

### ISSUE THREAD

**Issue by liyakun** [openbudgets/platform#48]
@larjohn It seems there is a problem with indigo after your updates, could you have a look when you have time? thanks.

When you access `http://eis-openbudgets.iais.fraunhofer.de/indigo/`, you will get `Invalid Host header`.

**Comment by larjohn** [comment]
This was expected. You should define the specific host instead of --host 0.0.0.0. 
It should probably be   --host eis-openbudgets.iais.fraunhofer.de

**Comment by liyakun** [comment]
@larjohn do you mean change it in https://github.com/openbudgets/integration/blob/master/docker-config/indigo/start.sh?

**Comment by larjohn** [comment]
Yes

**Comment by liyakun** [comment]
@larjohn This is strange, it works before with this setting. I think this is only for the app listening on the container port, it should have no influence on the host, right?

By the way, once I set the host to `--host eis-openbudgets.iais.fraunhofer.de`, the services on Fraunhofer server will not work.

**Comment by larjohn** [comment]
@liyakun this is all related to https://github.com/angular/angular-cli/issues/6070. I have tried the `disableHostCheck: true` workaround locally and it seems to work. We can go with this temporarily and go for something more convenient later on.

To sum it up, you can use     `ng serve --host 0.0.0.0 --disableHostCheck=true`

**Comment by liyakun** [comment]
@larjohn great, thanks, I already updated it on the server.
