### ISSUE TITLE
Don't accept any old domain on the production server

### ISSUE THREAD

**Issue by pwalsh** [openbudgets/platform#49]
# Description

In prep for #46 I set up a CNAME for `apps.openbudgets.eu` to point to the Fraunhofer servers. 

However, even with no configuration, the server will accept this domain and return a valid response, which, at time of writing, is:

```
{
  "site-map": "htt://localhost:5000/site-map",
  "whoami": "This is the data analysis mining backend of OpenBudgets.eu"
}
```

Ideally, we do not want anyone on the Internet to be able to point any domain at the server. The desired configuration would be to prevent such requests on the proxy server (nginx in this case).

# Tasks

- [x] Return an appropriate response header when requests arrive from an unknown domain.

**Comment by liyakun** [comment]
@pwalsh I use the following setting to response to unknow domain request
`server {
        listen          80;
        server_name     _;
        return          444;
    }
`
