### ISSUE TITLE
FDP2RDF pipeline for any FDP datapackage

### ISSUE THREAD

**Issue by HimmelStein** [openbudgets/platform#5]
After the FDP2RDF pipeline (v.0.2.5) is successfully imported into the Linkedpipes, we are moving on to develop a general FDP2RDF pipeline. To ease the development of this general pipeline, we follow three steps. 

(1) step one: using FDP datapackage created by the current Openspending wizard as the input to the current FDP2RDF pipeline, check results (we should see problems, as in current pipeline, mapping between OS-types and OBEU types are hard coded, and only parts of the OS-types are coded) [finish this week]

(2) step two: identify a simple way to transform any given FDP datapackage into RDF. One possibility is to design a FDP2RDF pipeline (can be a new one), which directly turns OS types into IRI (simply by adding a prefix and some simple string operation), and creates RDF datasets. check results [2 weeks] 

(3) step three: transform OS types, as many as possible, into OBEU types --- one possibility is to update the OS-types in datapackage.json before sending to the FDP2RDF pipeline [2 weeks]

**Comment by marek-dudas** [comment]
A few comments:
- the current FDP2RDF pipeline was developed as a general FDP2RDF pipeline, that should be able to transform any FDP package (following FDP specification) to OBEU RDF datamodel
- there might be some OS types that are not covered by FDP specification, which are thus transformed just to general DCV dimension properties and are not mapped to possible OBEU properties with the same meaning. That can be easily and quickly fixed by extending the current pipeline once such mappable OS types are identified.
- Jindřich just gave me an advice how to make the FDPtoRDF mapping in the pipeline more explicit and easy to see in one place. Such change can be done quickly and in any case, it will make maintenance of the current pipeline easier. Maybe you will like it and we won't have to developed a new pipeline, which in my opinion would take much more than two weeks.

I think that what is described as step two is similar to what the current pipeline does in the beginning: it turns everything into RDF, mostly by just adding a prefix. The hard part is turning this initial RDF into RDF conforming to OBEU datamodel, such as merging values from multiple columns describing the same dimension into one RDF object, turning literal values into skos instances, creating skos hierarchy, linking values from different tables according to foreign keys etc.

I am not sure if I understand step three. What is clear to me is that the goal is to transform OS types to corresponding OBEU values whenever possible. What does updating OS-types in datapackage.json mean?

**Comment by HimmelStein** [comment]
@marek-dudas thanks for the feedback. Let us run some concrete examples on the pipeline first. Based results, we will figure out the most efficient (also simple) solution. Some of the hard parts (you mention) can be addressed afterwards. e.g. using different pipelines, instead solving all hard tasks in one pipeline.

**Comment by HimmelStein** [comment]
@marek-dudas @mlukasch we run the pipeline (v0.2.6) with the ESIF sample dataset https://github.com/openbudgets/pipeline-fragments/blob/master/FDPtoRDF/test/test1/datapackage.jsonld , which contains three amount columns (EU amount, national amount, and total amount). The RDF results can be seen at the Fuseki server. 
The pipeline treats the original csv files as three tables, each has one of the three amount values. The four rows of the three tables are named b0, b1, b2, b3. We do not know which amount is associated with which table. e.g. 
"b1" , "http://data.openbudgets.eu/ontology/dsd/measure/amount" , "319794.6" ,
 "b1", "http://data.openbudgets.eu/ontology/dsd/measure/amount" , "310196.35" ,
 "b1" , "http://data.openbudgets.eu/ontology/dsd/measure/amount" , "629990.95" ,
All these rows shall have a unique name. for example, b0 - b3, b4 - b7, b8-11. 
AT-AT-AT as the value of the administrator dimension. one AT would be enough. 
do I understand correctly?

**Comment by HimmelStein** [comment]
@marek-dudas  @mlukasch with regards to the testing and evaluation of the FDP2RDF pipeline, it would be helpful to connect it to the pipeline developed for data inconsistency checking (D2.2), before push to Fuseki triple store. That is, the consistency of RDF will be checked by that pipeline before push to Fuseki triple.

**Comment by marek-dudas** [comment]
Regarding the multiple measures issue, I have created a [separate issue](https://github.com/openbudgets/pipeline-fragments/issues/7) for that in the pipeline-fragments repository. I think that it is better to post such issues directly there, so we won't lose track of them. I should be able to fix the issue soon.

Regarding data inconsistency checking pipeline, we are using it to test the FDP2RDF pipeline. Using it to check each FDP2RDF result before pushing further sounds like a good idea.

Regarding even more previously mentioned "hard issues" in the FDP2RDF pipeline, none of them is future work, all have been implemented. Future work is only further debugging and fixing, like in the case of multiple measures.

**Comment by HimmelStein** [comment]
@marek-dudas @jindrichmynarz  @akariv @badmotor it is great that the FDP2RDF pipeline is easy for maintenance. What we mainly concerned in Thessaloniki was mainly on this issue. It would be great that you can describe how to maintain/extend the pipeline in the document.

**Comment by HimmelStein** [comment]
@marek-dudas  have you tested Version 0.3.1 at the Fraunhofer server? at the last stage 'File to SCP' reported Cann't connect to host. @mlukasch have you encountered similar problem?
I checked /srv2/obeu/integration/volumes/linkedpipes/data/lp/etl/working/data/.., RDF triples were generated.

**Comment by marek-dudas** [comment]
The File to SCP has to be configured (hostname, username, password) according to the Fraunhofer server settings, which I do not know. I suppose @mlukasch just haven't done that yet?

**Comment by schmaluk** [comment]
Sorry, some Firewall issue. Am working on that.

**Comment by schmaluk** [comment]
Should be fixed. Files get stored /srv2/lpdata

**Comment by pwalsh** [comment]
@akariv do you have what you need to push data from OS to this web service?

**Comment by HimmelStein** [comment]
@marek-dudas FDP2RDF v0.3.1 run with success at the Fraunhofer server. Its RDF output is also pushed to Fuseki triple-store. The test datapackage.jsonld is https://github.com/openbudgets/pipeline-fragments/blob/master/FDPtoRDF/test/test1/datapackage.jsonld 
The multiple measures are represented correctly. 
I fail to find the date value "2014", which should be the value of _:b11 
_b:12, _b:13, _b:14 only appear as 'object', not clear to what they should refer.

**Comment by mlukasch** [comment]
@akariv @pwalsh Not urgent atm but want to avoid that you have to Change later the code again. 
Do you have an idea about how to protect the endpoint on our Server for triggering the FDP-to-Rdf-pipeline? (For testing reasons it is practical atm to be public.) But in production only OpenSpending should be able to call this endpoint. 
Access can be restricted by the IP-Address of OpenSpending in nginx. Would some kind of additional authentication be needed here (?)

**Comment by schmaluk** [comment]
@akariv @pwalsh Not urgent atm but want to avoid that you have to Change later the code again. 
 Do you have an idea about how to protect the endpoint on our Server for triggering the FDP-to-Rdf-pipeline? (For testing reasons it is practical atm to be public.) But in production only OpenSpending should be able to call this endpoint. 
 Access can be restricted by the IP-Address of OpenSpending in nginx. Would some kind of additional authentication be needed here (?)

**Comment by pwalsh** [comment]
@mlukasch 

IP address will not work (OpenSpending, like many other web apps, does not have a fixed IP address for all time).

The common approach would be that a service (LP-ETL in this case) would issue auth tokens, or at a pinch implement [Basic Auth](https://en.wikipedia.org/wiki/Basic_access_authentication), for clients who integrate with the service.

**Comment by jakubklimek** [comment]
@pwalsh Can the Basic auth be done in nginx outside of LP-ETL? I think Apache Fuseki also leaves security to other tools so it should be doable outside, especially when we are talking about one specific POST request.

**Comment by pwalsh** [comment]
@jakubklimek oh yes, of course, that is what I'd imagine the implementation to be, as I know that LP-ETL does not offer such features.

**Comment by marek-dudas** [comment]
Just a progress report: the latest FDPtoRDF pipeline v0.4.1 (https://github.com/openbudgets/pipeline-fragments/commit/72365e8c594708b3714e5371136bd53281eb5850) should have all up-to-now-discussed suggestions implemented, so please use this version for any further tests. I also added a brief [documentation with mapping overview and examples](https://github.com/openbudgets/pipeline-fragments/blob/master/FDPtoRDF/Documentation.md) reflecting the current situation. Further work from my side is more intensive testing and detailed documentation.

**Comment by pwalsh** [comment]
@badmotor @marek-dudas I'm closing this. It must be out of date, and any specific issues can be raised with distinct issues.
