### ISSUE TITLE
Rudolf not working correctly

### ISSUE THREAD

**Issue by liyakun** [openbudgets/platform#50]
Rudolf does not return any result from search api.
`http://eis-openbudgets.iais.fraunhofer.de/search/package?size=10000`

**Comment by larjohn** [comment]
Have you already run the search:load command? I think it is included in the
docker config but needs some time to finish.

**Comment by liyakun** [comment]
@larjohn It seems that indigo default loads 100 very slow with the following api call.
`http://eis-openbudgets.iais.fraunhofer.de/search/package?q=""&size=100&from=0`

**Comment by liyakun** [comment]
@larjohn It is working correctly now.
