### ISSUE TITLE
os-packager always "Waiting in queue for an available processor"

### ISSUE THREAD

**Issue by liyakun** [openbudgets/platform#52]
![image](https://user-images.githubusercontent.com/7370334/28023782-26557658-658f-11e7-8687-9a1fd93d1d36.png)
@akariv I tried to upload a file to through our deployment of [os-packager](http://apps.openbudgets.eu/packager/), but it stops in waiting for available processor, like shown in the above figure. I am not sure where the problem happens, do you have any idea?

**Comment by liyakun** [comment]
It ends up in "TypeError: Failed to fetch".
![image](https://user-images.githubusercontent.com/7370334/28025025-88f6a8e2-6592-11e7-8043-7755f66d55bc.png)

**Comment by akariv** [comment]
There was a stuck queue handler yesterday, that's supposed to be fixed now.

**Comment by liyakun** [comment]
@akariv thanks, it works now.
