### ISSUE TITLE
RDFBrowser: missing template error when resource is not found

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/platform#53]
When an unknown IRI in the <http://data.openbudgets.eu/resource> namespace is dereferenced, such as <http://data.openbudgets.eu/resource/codelist/oc-qsn-functional-class> (from [OpenCoesione's DSD](https://github.com/openbudgets/datasets/blob/master/OpenCoesione/dsd/OC-2007-2013-DSD.ttl)), RDFBrowser shows an error about a missing template:

```
ErrorException in FileViewFinder.php line 137:
View [layouts.browser_partials.htmlheader] not found. (View: /var/www/RDFBrowser/resources/themes/obeu/views/errors/noResource.blade.php)
```

**Comment by skarampatakis** [comment]
Thank you for pointing out. I have fixed the issue on OBEU theme. 
@liyakun could you update RDFBrowser and check?

**Comment by liyakun** [comment]
@skarampatakis RDFBrowser has been updated on the FHG server, it works fine now.
