### ISSUE TITLE
Why data.openbudgets.eu bans LP-ETL?

### ISSUE THREAD

**Issue by jindrichmynarz** [openbudgets/platform#54]
When I request an IRI from data.openbudgets.eu by LP-ETL, I get an HTTP 403 Forbidden error:

```
The owner of this website (data.openbudgets.eu) has banned your access based on your browser's signature (3846390777d615b9-ua21).
```

Why is LP-ETL banned by data.openbudgets.eu?

**Comment by skarampatakis** [comment]
@jindrichmynarz could you tell us what IRI you requested? I suppose it is a resource IRI, served by RDFBrowser, so we could check the logs, however the error message does not belong to RDFBrowser.

Searching a bit I believe it maybe something with some cloudflare setting

https://support.cloudflare.com/hc/en-us/articles/200171806-Error-1010-The-owner-of-this-website-has-banned-your-access-based-on-your-browser-s-signature

@pwalsh could you check?

**Comment by jindrichmynarz** [comment]
I requested the <http://data.openbudgets.eu/resource/codelist/kae-ota-esodwn-2014> IRI, but the ban seems  to apply to any IRI served by RDFBrowser.

LP-ETL sends a vanilla User-Agent "Java/1.8.0_131". I already suggested providing a more specific User-Agent string in linkedpipes/etl#449.

**Comment by skarampatakis** [comment]
I was looking on the server logs and never found such request. That probably means that the request never arrives on the server and it is cut on cloudflare. So it may be related with the issue I mentioned above. 

Could you temporaly change the User-Agent request header to something like 
```
Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
```

so we can confirm the assumption?

**Comment by jindrichmynarz** [comment]
I confirmed it with `curl`. Requesting the IRI with the LP-ETL's User-Agent results in the ban:

```bash
curl -A "Java/1.8.0_131" http://data.openbudgets.eu/resource/codelist/kae-ota-esodwn-2014
```

While standard `curl` User-Agent works fine:

```bash
curl http://data.openbudgets.eu/resource/codelist/kae-ota-esodwn-2014
```

**Comment by jindrichmynarz** [comment]
Also confirmed via the HTTP GET list component in LP-ETL. Spoofing its User-Agent string allows to avoid the ban.

**Comment by skarampatakis** [comment]
So it is definetely related with [Browser Integrity Check ](https://support.cloudflare.com/hc/en-us/articles/200170086-What-does-the-Browser-Integrity-Check-do-). 

Either @pwalsh could turn it off(but I think we should not), either change LP's agent header. I tried to find the headers that Cloudflare would accept with no success. Maybe Paul has some hints.

**Comment by pwalsh** [comment]
@skarampatakis @jindrichmynarz I've removed Cloudflare's proxying now on both app.* and data.* for our domain. I think this is the best approach for this platform, although I agree with @skarampatakis that in general for developing web services, we should not have to disable such a feature.

@jindrichmynarz let me know if it works ok now.

**Comment by jindrichmynarz** [comment]
@pwalsh: Thanks, LP-ETL can now request data from data.openbudgets.eu. Nevertheless, I think that LP-ETL should provide a specific `User-Agent` (tracked in the linked LP-ETL issue), so that Cloudflare accepts its requests.
