### ISSUE TITLE
Indigo-Explorer freezes at first load

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/platform#56]
Indigo seems to freeze at first load. When visit apps.openbudgets.eu it first shows a progress bar. 
After finish the browser becomes unresponsive for some time (~10 secs) and afterwards the datasets are presented. 

While scrolling down there seems also to be some freezes. I checked the console and there seems to be some AJAX calls to localhost as can be seen below which ofcourse always fail.

![image](https://user-images.githubusercontent.com/2419820/28666478-29574950-72d0-11e7-96b2-aef8d4ec5aa5.png)

**Comment by larjohn** [comment]
OS, CPU, RAM?

**Comment by skarampatakis** [comment]
Ubuntu 16.4.2, i5 3.1Ghz, 8GB RAM, 256GB SSD

**Comment by larjohn** [comment]
From the picture above, it seems the vector.bundle.js takes too long to download, as it is a few megabytes. The following has been done to alleviate it:

1. Compression (gzip) has been enabled in `nginx ` - should improve the overall speed of the platform
2. The` angular-cli` test server has been abandoned for a separate `nginx` docker image, where the static files are served. These files are built with the `-aot` flag, which makes them even smaller and performant.

This means the indigo Dockerfile has been built from scratch, so it needs to be refreshed (@liyakun)  in the public server in order for you to see the overall performance gain.

**Comment by liyakun** [comment]
@larjohn The server has been updated.

**Comment by larjohn** [comment]
@liyakun Thanks!

@skarampatakis can you have a look?

**Comment by skarampatakis** [comment]
I still get this kind of errors which freeze for some time the app.

![image](https://user-images.githubusercontent.com/2419820/28792260-b23e429a-7637-11e7-8fce-a831236ffa68.png)

It is making continuously a call to localhost.

**Comment by larjohn** [comment]
This was due to using the developer-oriented ng serve. It should do so now. Have you refreshed the page with CTRL+F5? Even the "vendor.bundle.js" is not the case anymore, it should have some hash in the name.

![image](https://user-images.githubusercontent.com/1288985/28800285-aefb0a56-7654-11e7-89e7-ffbe6643d95a.png)

**Comment by skarampatakis** [comment]
Now I get these errors
![image](https://user-images.githubusercontent.com/2419820/28812420-59791174-769d-11e7-8d4c-41af3d943042.png)

which again cause the app to freeze from time to time. It is happening on scrolling down the datasets.

**Comment by skarampatakis** [comment]
And I also get these errors on the console
![image](https://user-images.githubusercontent.com/2419820/28812528-c42b7e3a-769d-11e7-8da5-0040772b2a71.png)

**Comment by larjohn** [comment]
These are unrelated with this issue. Probably someone restarted the server and indexing didn't work. Does it work now for you @skarampatakis ?
