### ISSUE TITLE
descriptive statistics return http 500 at front side

### ISSUE THREAD

**Issue by HimmelStein** [openbudgets/platform#63]
please use the following link and check http://apps.openbudgets.eu/cube/analytics/bonn-budget-2019__40559/descriptive_statistics/facts?amounts=amount&dimensions=operationCharacter.prefLabel%7CbusinessArea.prefLabel%7Corganization.organization%7CfunctionalClassification.prefLabel%7CbudgetPhase.prefLabel&json_data=http%3A%2F%2Fapps.openbudgets.eu%2Fapi%2F3%2Fcubes%2Fbonn-budget-2019__40559%2Ffacts%3F

**Comment by liyakun** [comment]
![error](https://user-images.githubusercontent.com/7370334/29830762-69b26bec-8ce3-11e7-9d09-603233360cff.png)
I attached one screenshot about where the error happens.

**Comment by skarampatakis** [comment]
found this on the logs
```
PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /var/www/rudolf/vendor/symfony/debug/Exception/FatalErrorException.php on line 1" while reading response header from upstream, client: 155.207.200.73, server: apps.openbudgets.eu, request: "GET /api/3/cubes/bonn-budget-2019__40559/facts? HTTP/1.1", upstream: "fastcgi://172.20.0.18:8890", host: "apps.openbudgets.eu
```

**Comment by larjohn** [comment]
It seems that parseJSON times out:

EasyRdf_Sparql_Result->parseJson() in Result.php line 71

A solution would be to paginate results, as this dataset is HUGE.


![image](https://user-images.githubusercontent.com/1288985/30524036-a409e390-9bf4-11e7-9059-4529139d28a9.png)

**Comment by HimmelStein** [comment]
thanks, we will try to use pagination

**Comment by wk0206** [comment]
@larjohn @HimmelStein I read the log, seems it is the mining server in Greece or Ruldorf out of memory, I am not sure what our side can do with it, as you know, DAM only deliver a Ruldorf link , or a link of JSON file. So from my point of view, DAM can not paginate the input data(because it is a link from Ruldorf). If it is the case the output data is too big, then maybe DAM can do some pagination. If you have anything our side can do, please tell me.

**Comment by skarampatakis** [comment]
@wk0206 Have you managed to make DAM work with the OpenCPU docker container?

**Comment by HimmelStein** [comment]
@skarampatakis @liyakun Yakun made a docker container for OpenCPU https://github.com/openbudgets/integration/tree/master/docker-config

**Comment by liyakun** [comment]
@skarampatakis yes, DAM now works with OpenCPU deployed on FHG server.

**Comment by skarampatakis** [comment]
On the php.ini for rudolf the memory limit is defined to 128M. Please change this to -1 and test again

**Comment by liyakun** [comment]
update on fhg server from 128M to -1.

**Comment by wk0206** [comment]
The link is working now @HimmelStein 
One more thing is , indigo seems not stop running after the result is on the screen.
![indigo](https://user-images.githubusercontent.com/5684265/30645243-5de8ade2-9e15-11e7-9fb9-c80d28908c56.png)

**Comment by skarampatakis** [comment]
Reduce the limit to 1G or 2G.

**Comment by liyakun** [comment]
reduced to 2G.

**Comment by liyakun** [comment]
@wk0206 I was updating the server, Indigo should work normally now.

**Comment by skarampatakis** [comment]
Can we close this?
