### ISSUE TITLE
execution button of Outlier detection LOF is always disabled using Bonn dataset

### ISSUE THREAD

**Issue by HimmelStein** [openbudgets/platform#64]
Please use the following link and check
http://apps.openbudgets.eu/cube/analytics/bonn-budget-2022__293d8/outlier_detection/LOF_AGGREGATE

**Comment by larjohn** [comment]
Please use the short hint on top of parameters to build your request.
Working (not necessarily pretty) example:

https://apps.openbudgets.eu/cube/analytics/bonn-budget-2022__293d8/outlier_detection/LOF_AGGREGATE?BABBAGE_AGGREGATE_URI=https%3A%2F%2Fapps.openbudgets.eu%2Fapi%2F3%2Fcubes%2Fbonn-budget-2022__293d8%2Faggregate%3Fdrilldown%3DeconomicClassification.prefLabel%257CprofitCenter.prefLabel%26aggregates%3Damount.sum%26pagesize%3D30&coloringAttribute=economicClassification.prefLabel&groupingAttribute=profitCenter.prefLabel
