### ISSUE TITLE
When user selects an insutiable data-mining service for a selected data, ...

### ISSUE THREAD

**Issue by HimmelStein** [openbudgets/platform#67]
When a user selects an unsuitable data-mining service for a selected data, what will the system inform the user? e.g. change the back ground color to red?

tested link: http://apps.openbudgets.eu/cube/analytics/eu_allocations_per_ms_2014_2020__bc728/clustering/facts

**Comment by larjohn** [comment]
This was originally intended as a functionality included in DAM. That is why I had requested the available algorithms to be under the dataset and not general ones. In that case, the available algorithms visible to indigo would only be the applicable ones.

**Comment by larjohn** [comment]
See https://github.com/openbudgets/DAM/issues/13
