### ISSUE TITLE
Loading time issues

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/platform#69]
I got this today. 

![image](https://user-images.githubusercontent.com/2419820/30605244-095f38bc-9d76-11e7-94d4-6d0b61baff06.png)

Browser was responsive again after hardly 3-4 minutes.
I think that the number of datasets shown should be reduced.

**Comment by larjohn** [comment]
The most recent version of Firefox (codenamed "Quantum") seems to load Indigo in reasonable time.
