### ISSUE TITLE
Request URL 404 Not Found

### ISSUE THREAD

**Issue by kleanthisk10** [openbudgets/platform#71]
When i tried to perform descriptive statistics in a dataset on platform, provided in [this link](http://apps.openbudgets.eu/cube/analytics/budget-athens-expenditure-2010__6a8b3/descriptive_statistics/facts?amounts=amount&dimensions=budgetPhase.prefLabel%7CfunctionalClassification.prefLabel%7CadministrativeClassification.prefLabel&json_data=http%3A%2F%2Fapps.openbudgets.eu%2Fapi%2F3%2Fcubes%2Fbudget-athens-expenditure-2010__6a8b3%2Ffacts%3Ffields%3Damount%2CbudgetPhase.prefLabel%2CfunctionalClassification.prefLabel%2CadministrativeClassification.prefLabel)
i got a wrong url request: 
http://apps.openbudgets.eu/ocpu/ocpu/library/DescriptiveStats.OBeu/R/open_spending.ds/print
the correct url is:
http://apps.openbudgets.eu/ocpu/library/DescriptiveStats.OBeu/R/open_spending.ds/print

**Comment by skarampatakis** [comment]
I think this is fixed now. Can you check?
