### ISSUE TITLE
Graph naming issue

### ISSUE THREAD

**Issue by HimmelStein** [openbudgets/platform#9]
@marek-dudas @jindrichmynarz @jakubklimek @mlukasch   consider the following case.
there is a rdf dataset for city X0 of year Y0, and stored as a named graph at Fuseki server, the graph name is something like http://.../X0Y0. 
the rdf dataset for city X0 of year Y1, and stored as a named graph at Fuseki server, the graph name is something like http://.../X0Y1.  

It should happen that within the two graphs, they share common dimensions and dimension values, except that one contains 'X0Y0' while the other contains 'X0Y1'. If users just name the two graphs as http://.../X0, without adding the temporal information (Y0, Y1), there will be a conflict.

Any consideration on such case?

**Comment by jindrichmynarz** [comment]
I don't see this as a problem. We specify the IRI pattern for named graphs as `http://data.openbudgets.eu/resource/dataset/{dataset ID}`. In case of FDP2RDF pipeline, the dataset ID is derived from the OpenSpending ID. If I recall correctly, OpenSpending uploader enforces unique IDs, which in turn makes the named graph IRIs unique. If there is a dataset that is ingested using custom ETL process, then the choice of the dataset ID is up to the ETL developer, who must pick a unique ID.

**Comment by jakubklimek** [comment]
Could you be more specific and provide examples? I don't see the issue.
Also when do you think this would become the issue? When creating the data or when consuming it?

**Comment by marek-dudas** [comment]
I was writing a comment which is now probably irrelevant considering @jindrichmynarz reply. But here it is anyway:

_From the FDP2RDF pipeline point of view, a simple solution would be adding a timestamp at the end of the graph and dataset names. It would make the result a little bit less user friendly. However, in this particular case described above, I think there would be actually no conflict if the dates were specified for each source row separately. The dsd, dimension etc. definitions would be duplicated, but that is not an issue in RDF. On the other hand, if the date (year) was specified in the FDP fiscalPeriod property, then there would be an actual conflict, since that is bound to the dataset, so we would have two conflicting fiscalPeriod values._

**Comment by HimmelStein** [comment]
@jakubklimek when consuming data (as Marek described, if conflict exists) 
@jindrichmynarz @akariv @mlukasch  where can we find unique IDs from OpenSpending uploader? it should be within the datapackage.json. here is a real sample datapackage.json generated by OS wizard https://github.com/openbudgets/pipeline-fragments/blob/master/FDPtoRDF/test/test1/datapackage.jsonld

**Comment by jindrichmynarz** [comment]
The dataset ID is in the `name` attribute (see [here](http://fiscal.dataprotocols.org/spec/#package-metadata)).

**Comment by HimmelStein** [comment]
"If there is a dataset that is ingested using custom ETL process, then the choice of the dataset ID is up to the ETL developer, who must pick a unique ID. " -- that is the issue:
How can an ETL developer know that she/he picks a unique ID or not? it can happen that the developer should use a unique ID, but neglected; it can also happen that the developer just uses an existing ID to update values.  Marek has commented on the issue. As Jakub suggested, I will design some testing to clarify.

**Comment by jakubklimek** [comment]
In that case the developer is from the OBEU project and I believe we can keep track of used IDs as they usually correspond to the folders in https://github.com/openbudgets/datasets

**Comment by jindrichmynarz** [comment]
> How can an ETL developer know that she/he picks a unique ID or not?

Once the dereferencing (#2) is setup (note: currently not working), the ETL developer can dereference a IRI (e.g., `http://data.openbudgets.eu/resource/dataset/budget-of-the-european-union-2014`) to see whether is is already used.

A slightly more involved test would be to query the SPARQL endpoint. For example, if the following returns `true`, then the IRI `http://data.openbudgets.eu/resource/dataset/budget-of-the-european-union-2014` was already used:

``` sparql
ASK {
  <http://data.openbudgets.eu/resource/dataset/budget-of-the-european-union-2014> ?p [] .
}
```

**Comment by HimmelStein** [comment]
@jindrichmynarz these are definitely effective methods.  As ETL pipelines are manually designed, point here is that not to forget to check uniqueness (when needed).   but, ETL developers are also humans, they may forget....  
@marek-dudas was your comment above written for the case I described above, or copied here from other place?

**Comment by jindrichmynarz** [comment]
I see your point. Perhaps we can agree on a process of pushing data into the OpenBudgets.eu platform. For example, each pipeline would have to end with HTTP POST containing the resulting data to a "clearance" pipeline that could perform some safety checks, such as testing whether the dataset IRI is unique or whether the DCV integrity constraints are satisfied. This way we can offload some of the burden on ETL developers.

**Comment by HimmelStein** [comment]
that is a nice solution! That is, @mlukasch pipeline fragments developed at Task 2.2 shall also be imported to the Linkedpipe ETL at the fraunhofer server. 
Can we close this issue here, and open another issues for 'clearance' pipelines and integration (if necessary)?

**Comment by marek-dudas** [comment]
@HimmelStein my previous comment was written for the case you described above.

**Comment by jindrichmynarz** [comment]
@HimmelStein You are the author of the issue, so you decide if it should be closed.

**Comment by HimmelStein** [comment]
let us close the issue. thanks for the quick and fruitful responses!
